#!/usr/bin/env python3
"""Write unified JTBD records for security + authentication books."""
import csv
import json
from pathlib import Path

OUT = Path("/home/ahoffer/git/openshift-docs/analysis/topicmap/security-auth")
DOC = "security-auth-combined.adoc"

# Evidence uses combined-file line ranges (from topic map boundaries + content offsets)
records = [
    # --- MAIN JOBS ---
    {
        "doc": DOC,
        "section": "Understanding container security",
        "job_statement": "When bringing containerized workloads into production, I want to secure the full supply chain from trusted images through build and deployment, so I can reduce vulnerability exposure and meet organizational security standards.",
        "job_type": "core",
        "persona": "Platform administrator",
        "job_map_stage": "Secure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": [],
        "related_jobs": [
            "Demonstrate and maintain regulatory compliance posture",
            "Authenticate users and API clients to the cluster",
        ],
        "desired_outcomes": [
            "Minimize time to detect and replace vulnerable container images",
            "Ensure container images and builds use trusted sources",
            "Reduce likelihood of deploying unverified or outdated image content",
        ],
        "evidence": f"{DOC} -> Section 'Understanding container security', lines 523-900 [modules: security-understanding; books: security]",
        "notes": "Spans container_security topics: content, registries, build, deploy, signatures. Sources: security/container_security/*.adoc",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Understanding host and VM security",
        "job_statement": "When operating OpenShift on bare metal or virtualized infrastructure, I want to harden hosts and the container platform OS, so I can shrink the attack surface at the infrastructure layer.",
        "job_type": "core",
        "persona": "Platform administrator",
        "job_map_stage": "Secure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": [],
        "related_jobs": ["Constrain workload security context and admission"],
        "desired_outcomes": [
            "Ensure nodes run on hardened operating system baselines",
            "Reduce likelihood of host-level compromise affecting workloads",
        ],
        "evidence": f"{DOC} -> Section 'Understanding host and VM security' / 'Hardening Red Hat Enterprise Linux CoreOS', lines 1053-2100 [books: security]",
        "notes": "Includes RHCOS/FCOS hardening assemblies.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Understanding authentication",
        "job_statement": "When users and automation interact with the cluster API, I want reliable authentication that identifies every caller, so I can enforce authorization and maintain an accurate audit trail.",
        "job_type": "core",
        "persona": "Cluster administrator",
        "job_map_stage": "Secure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": [],
        "related_jobs": [
            "Define and enforce access permissions on cluster resources",
            "Integrate enterprise identity sources with the cluster",
        ],
        "desired_outcomes": [
            "Ensure unauthenticated or invalid requests are rejected",
            "Minimize ambiguity about which user or service account performed an action",
        ],
        "evidence": f"{DOC} -> Section 'Understanding authentication', lines 83986-84650 [module: rbac-users, oauth-server-overview; books: authentication, security/security-platform]",
        "notes": "Cross-book: authentication book plus 'Authentication and authorization' in security-platform.adoc.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Understanding identity provider configuration",
        "job_statement": "When my organization relies on corporate directories or external IdPs, I want to integrate those identity sources with OpenShift, so I can centralize login and group membership for cluster access.",
        "job_type": "related",
        "persona": "Cluster administrator",
        "job_map_stage": "Configure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": ["Authenticate users and API clients to the cluster"],
        "related_jobs": [
            "Define and enforce access permissions on cluster resources",
            "Sync directory groups into OpenShift",
        ],
        "desired_outcomes": [
            "Minimize manual user provisioning on the cluster",
            "Ensure identity mappings reflect enterprise directory structure",
        ],
        "evidence": f"{DOC} -> Sections 'Understanding identity provider configuration' / identity provider assemblies, lines 86728-93350 [books: authentication]",
        "notes": "Covers htpasswd, LDAP, OIDC, GitHub, Google, request-header, Keystone, and related IdP assemblies.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Using RBAC to define and apply permissions",
        "job_statement": "When multiple teams share a cluster, I want to define who can perform which actions in which projects, so I can enforce least privilege and isolate tenant workloads.",
        "job_type": "core",
        "persona": "Cluster administrator",
        "job_map_stage": "Secure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": ["Authenticate users and API clients to the cluster"],
        "related_jobs": [
            "Constrain workload security context and admission",
            "Isolate containers with multitenancy",
        ],
        "desired_outcomes": [
            "Reduce likelihood of unauthorized API actions",
            "Ensure permissions align with project and cluster boundaries",
        ],
        "evidence": f"{DOC} -> Section 'Using RBAC to define and apply permissions' / 'Isolating containers with multitenancy', lines 6723-7300 and 94329-95300 [books: authentication, security]",
        "notes": "RBAC in authentication book; multitenancy concept in security-platform.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Understanding and managing pod security admission",
        "job_statement": "When running diverse workloads on shared infrastructure, I want to restrict pod capabilities to approved security profiles, so I can prevent overly privileged containers from compromising the cluster.",
        "job_type": "core",
        "persona": "Platform administrator",
        "job_map_stage": "Secure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": ["Define and enforce access permissions on cluster resources"],
        "related_jobs": [
            "Manage security context constraints",
            "Enforce workload runtime security profiles",
        ],
        "desired_outcomes": [
            "Minimize pods running with excessive privileges",
            "Ensure pod security standards are enforced consistently per namespace",
        ],
        "evidence": f"{DOC} -> Section 'Understanding and managing pod security admission', lines 100315-101090 [books: authentication]",
        "notes": "Documents PSA modes/profiles and interaction with SCC controllers.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Understanding and creating service accounts",
        "job_statement": "When applications and operators need programmatic API access, I want to provision and govern service accounts and tokens, so I can automate workloads without sharing human credentials.",
        "job_type": "core",
        "persona": "Platform administrator",
        "job_map_stage": "Administer",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": ["Authenticate users and API clients to the cluster"],
        "related_jobs": [
            "Define and enforce access permissions on cluster resources",
            "Scope OAuth and service account tokens",
        ],
        "desired_outcomes": [
            "Ensure service accounts have minimal required permissions",
            "Reduce risk from long-lived or overly broad automation credentials",
        ],
        "evidence": f"{DOC} -> Sections on service accounts, bound tokens, token scoping, lines 95824-98920 [books: authentication]",
        "notes": "Includes service accounts as OAuth clients and bound service account tokens.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Replacing the default ingress certificate",
        "job_statement": "When cluster components and routes must trust custom or corporate CAs, I want to manage platform and ingress TLS certificates, so I can encrypt traffic and meet PKI policies.",
        "job_type": "core",
        "persona": "Cluster administrator",
        "job_map_stage": "Configure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": [],
        "related_jobs": [
            "Automate certificate issuance and renewal for workloads",
            "Manage secrets across the platform",
        ],
        "desired_outcomes": [
            "Ensure API and ingress endpoints present trusted certificates",
            "Minimize service disruption during certificate rotation",
        ],
        "evidence": f"{DOC} -> Certificate configuration and certificate type reference sections, lines 8918-17400 [books: security]",
        "notes": "Covers ingress/API certs, service serving certs, CA bundle, and certificate type reference topics.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Installing the cert-manager Operator for Red Hat OpenShift",
        "job_statement": "When workloads need automated TLS or integration with external CAs, I want to operate certificate and secrets management operators, so I can issue, rotate, and distribute credentials without manual intervention.",
        "job_type": "consumption",
        "persona": "Platform administrator",
        "job_map_stage": "Operate",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": ["Manage platform and ingress TLS certificates"],
        "related_jobs": ["Manage platform and ingress TLS certificates"],
        "desired_outcomes": [
            "Minimize manual certificate lifecycle tasks",
            "Ensure secrets are sourced from approved external systems when required",
        ],
        "evidence": f"{DOC} -> cert-manager Operator and External Secrets Operator sections, lines 43000-52000 approx. [books: security]",
        "notes": "Includes cert-manager, External Secrets Operator, and understanding-secrets-management.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Understanding compliance",
        "job_statement": "When my organization must meet regulatory or internal control frameworks, I want to assess and document cluster compliance against recognized profiles, so I can pass audits and prioritize remediation.",
        "job_type": "core",
        "persona": "Security/compliance officer",
        "job_map_stage": "Confirm",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": ["Establish a secure container supply chain"],
        "related_jobs": [
            "Monitor and investigate security-relevant cluster activity",
            "Enforce workload runtime security profiles",
        ],
        "desired_outcomes": [
            "Minimize time to produce evidence for compliance audits",
            "Reduce gaps between required controls and cluster configuration",
        ],
        "evidence": f"{DOC} -> Sections 'Understanding compliance' / Compliance Operator scan topics, lines 3605-4100 and 24735-27900 [books: security]",
        "notes": "Conceptual compliance content plus Compliance Operator scan/remediation assemblies.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Viewing audit logs",
        "job_statement": "When investigating security incidents or preparing audit evidence, I want to monitor and investigate security-relevant cluster activity using audit and security logs, so I can reconstruct who did what and detect policy violations.",
        "job_type": "core",
        "persona": "Cluster administrator",
        "job_map_stage": "Monitor",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": [],
        "related_jobs": [
            "Demonstrate and maintain regulatory compliance posture",
            "Deploy and configure the File Integrity Operator",
        ],
        "desired_outcomes": [
            "Minimize time to find relevant security events in logs",
            "Ensure audit records capture user, action, and resource context",
        ],
        "evidence": f"{DOC} -> Sections 'Viewing audit logs' / 'Configuring the audit log policy' / 'Monitoring cluster events and logs', lines 76354-78000 and 8380-8917 [books: security]",
        "notes": "Ties authentication activity to security monitoring; audit log abstract cites chronological security records.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Security Profiles Operator overview",
        "job_statement": "When I need defense-in-depth beyond RBAC and network policy, I want to enforce seccomp, SELinux, and related runtime controls on workloads, so I can limit exploit impact and align with hardened baselines.",
        "job_type": "core",
        "persona": "Platform administrator",
        "job_map_stage": "Secure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": ["Constrain workload security context and admission"],
        "related_jobs": [
            "Configure TLS security profiles",
            "Scan pods for vulnerabilities",
        ],
        "desired_outcomes": [
            "Reduce container syscall and privilege exposure",
            "Ensure workloads run with organization-approved security profiles",
        ],
        "evidence": f"{DOC} -> Security Profiles Operator, seccomp/TLS profile, pod vulnerability scan sections [books: security]",
        "notes": "SPO, cluster seccomp/TLS profiles, and pod vulnerability scanning.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "About disk encryption technology",
        "job_statement": "When persistent data must remain confidential if disks are lost or stolen, I want to encrypt nodes and volumes with managed keys, so I can meet data-protection requirements.",
        "job_type": "core",
        "persona": "Platform administrator",
        "job_map_stage": "Secure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": [],
        "related_jobs": ["Secure attached storage for workloads"],
        "desired_outcomes": [
            "Ensure data at rest is encrypted with recoverable key management",
            "Reduce risk of data exposure from physical media loss",
        ],
        "evidence": f"{DOC} -> NBDE and Tang Server Operator sections, lines 82000-83400 approx. [books: security]",
        "notes": "Network-Bound Disk Encryption topics and NBDE Tang Server Operator.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Securing networks",
        "job_statement": "When workloads communicate inside and outside the cluster, I want to segment traffic and protect ingress/egress paths, so I can contain breaches and control data flows.",
        "job_type": "related",
        "persona": "Platform administrator",
        "job_map_stage": "Secure",
        "granularity": "main_job",
        "parent_job": None,
        "prerequisites": [],
        "related_jobs": [
            "Define and enforce access permissions on cluster resources",
            "Manage platform and ingress TLS certificates",
        ],
        "desired_outcomes": [
            "Minimize unauthorized lateral movement between namespaces",
            "Ensure sensitive services are reachable only through approved network paths",
        ],
        "evidence": f"{DOC} -> Sections 'Securing networks' / 'Securing attached storage', lines 7335-8379 [books: security]",
        "notes": "Container security guide network and storage chapters.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    # --- USER STORIES (selected implementation paths) ---
    {
        "doc": DOC,
        "section": "Container image signatures",
        "job_statement": "When deploying images from Red Hat registries, I want to enable and verify image signature policies, so I can block unsigned or untrusted images from running on the cluster.",
        "job_type": "related",
        "persona": "Platform administrator",
        "job_map_stage": "Confirm",
        "granularity": "user_story",
        "parent_job": "Establish a secure container supply chain",
        "prerequisites": ["Configure trusted container registries"],
        "related_jobs": ["Control which image sources can be deployed"],
        "desired_outcomes": [
            "Reduce likelihood of running images lacking verifiable signatures",
        ],
        "evidence": f"{DOC} -> Section 'Container image signatures', lines 2112-3100 [books: security]",
        "notes": "Assembly: security-container-signature.adoc",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Configuring an LDAP identity provider",
        "job_statement": "As a cluster administrator, when my users authenticate against corporate LDAP, I want to configure an LDAP identity provider for OAuth, so they can log in with existing directory credentials.",
        "job_type": "related",
        "persona": "Cluster administrator",
        "job_map_stage": "Configure",
        "granularity": "user_story",
        "parent_job": "Integrate enterprise identity sources with the cluster",
        "prerequisites": ["Configure the internal OAuth server"],
        "related_jobs": ["Sync LDAP groups into OpenShift"],
        "desired_outcomes": [
            "Minimize duplicate identity stores for cluster login",
        ],
        "evidence": f"{DOC} -> LDAP identity provider and LDAP syncing sections, lines 88928-103868 [books: authentication]",
        "notes": "",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Configuring an OpenID Connect identity provider",
        "job_statement": "As a cluster administrator, when my organization standardizes on OIDC, I want to configure an OpenID Connect identity provider, so users authenticate through our corporate SSO.",
        "job_type": "related",
        "persona": "Cluster administrator",
        "job_map_stage": "Configure",
        "granularity": "user_story",
        "parent_job": "Integrate enterprise identity sources with the cluster",
        "prerequisites": [],
        "related_jobs": ["Enable direct authentication with an OIDC identity provider"],
        "desired_outcomes": [
            "Ensure OAuth tokens map to the correct OpenShift user identities",
        ],
        "evidence": f"{DOC} -> OIDC IdP and external-auth sections, lines 92888-94328 [books: authentication]",
        "notes": "",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Managing security context constraints",
        "job_statement": "As a platform administrator, when a workload needs elevated privileges, I want to manage security context constraints, so only approved pods receive privileged capabilities.",
        "job_type": "core",
        "persona": "Platform administrator",
        "job_map_stage": "Modify",
        "granularity": "user_story",
        "parent_job": "Constrain workload security context and admission",
        "prerequisites": ["Understand pod security admission profiles"],
        "related_jobs": [],
        "desired_outcomes": [
            "Reduce pods running with unintended privileged settings",
        ],
        "evidence": f"{DOC} -> Section 'Managing security context constraints', lines 98923-100314 [books: authentication]",
        "notes": "SCC content also referenced from security-platform admission section.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Compliance Operator scans",
        "job_statement": "As a compliance engineer, when I need CIS or other benchmark results, I want to run Compliance Operator scans with ScanSetting and ScanSettingBinding, so I can measure control effectiveness and track remediation.",
        "job_type": "core",
        "persona": "Security/compliance officer",
        "job_map_stage": "Confirm",
        "granularity": "user_story",
        "parent_job": "Demonstrate and maintain regulatory compliance posture",
        "prerequisites": ["Install the Compliance Operator"],
        "related_jobs": ["Tailor compliance profiles", "Manage Compliance Operator remediation"],
        "desired_outcomes": [
            "Minimize time to obtain standardized compliance scan results",
            "Reduce inconsistent scan results across heterogeneous nodes",
        ],
        "evidence": f"{DOC} -> Section 'Compliance Operator scans', lines 24735-25705 [books: security]",
        "notes": "",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Installing the File Integrity Operator",
        "job_statement": "As a security administrator, when I need to detect tampering on cluster nodes, I want to deploy and configure the File Integrity Operator, so I can alert on unexpected file changes.",
        "job_type": "consumption",
        "persona": "Security administrator",
        "job_map_stage": "Monitor",
        "granularity": "user_story",
        "parent_job": "Monitor and investigate security-relevant cluster activity",
        "prerequisites": [],
        "related_jobs": ["View and filter API audit logs"],
        "desired_outcomes": [
            "Reduce time to detect unauthorized modifications on nodes",
        ],
        "evidence": f"{DOC} -> File Integrity Operator sections, lines 30646-35000 approx. [books: security]",
        "notes": "",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Configuring the internal OAuth server",
        "job_statement": "As a cluster administrator, when I deploy or harden a cluster, I want to configure the internal OAuth server and clients, so interactive and programmatic login flows work securely.",
        "job_type": "consumption",
        "persona": "Cluster administrator",
        "job_map_stage": "Configure",
        "granularity": "user_story",
        "parent_job": "Authenticate users and API clients to the cluster",
        "prerequisites": [],
        "related_jobs": ["Configure OAuth clients", "Manage user-owned OAuth access tokens"],
        "desired_outcomes": [
            "Ensure OAuth token issuance uses the intended identity provider",
        ],
        "evidence": f"{DOC} -> OAuth configuration sections, lines 84613-86727 [books: authentication]",
        "notes": "",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Removing the kubeadmin user",
        "job_statement": "As a cluster administrator, after establishing durable admin access, I want to remove the kubeadmin bootstrap account, so I reduce exposure of a shared emergency credential.",
        "job_type": "related",
        "persona": "Cluster administrator",
        "job_map_stage": "Conclude",
        "granularity": "user_story",
        "parent_job": "Authenticate users and API clients to the cluster",
        "prerequisites": [
            "Define at least one other cluster-admin access path",
        ],
        "related_jobs": ["Define and enforce access permissions on cluster resources"],
        "desired_outcomes": [
            "Reduce likelihood of compromise via the kubeadmin account",
        ],
        "evidence": f"{DOC} -> Section 'Removing the kubeadmin user', lines 95348-95823 [books: authentication]",
        "notes": "",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "About the Cloud Credential Operator",
        "job_statement": "As a platform administrator, when OpenShift runs on a public cloud, I want to configure cloud credential modes for components, so operators can access cloud APIs without over-privileged static keys.",
        "job_type": "related",
        "persona": "Platform administrator",
        "job_map_stage": "Configure",
        "granularity": "user_story",
        "parent_job": "Manage machine identities for applications and automation",
        "prerequisites": [],
        "related_jobs": [],
        "desired_outcomes": [
            "Minimize use of long-lived cloud credentials on the cluster",
            "Ensure components receive only required cloud IAM permissions",
        ],
        "evidence": f"{DOC} -> Cloud Credential Operator sections, lines 103868-107997 [books: authentication]",
        "notes": "CCO content lives in authentication book but supports platform security posture.",
        "validation_status": "pass",
        "validation_flags": [],
    },
    {
        "doc": DOC,
        "section": "Protecting control plane with admission plugins",
        "job_statement": "As a platform administrator, when hardening the control plane, I want to understand and tune admission plugins and SCC defaults, so API requests that violate policy are rejected before workloads run.",
        "job_type": "related",
        "persona": "Platform administrator",
        "job_map_stage": "Secure",
        "granularity": "user_story",
        "parent_job": "Constrain workload security context and admission",
        "prerequisites": [],
        "related_jobs": ["Define and enforce access permissions on cluster resources"],
        "desired_outcomes": [
            "Reduce policy-violating resources admitted to the cluster",
        ],
        "evidence": f"{DOC} -> Section 'Protecting control plane with admission plugins', lines 6723-7230 [books: security]",
        "notes": "security-platform.adoc admission and SCC overview.",
        "validation_status": "pass",
        "validation_flags": [],
    },
]

# Fix parent_job references to match shortened main job titles used in parent_job field
PARENT_MAP = {
    "Establish a secure container supply chain": "Establish a secure container supply chain",
    "Authenticate users and API clients to the cluster": "Authenticate users and API clients to the cluster",
    "Integrate enterprise identity sources with the cluster": "Integrate enterprise identity sources with the cluster",
    "Define and enforce access permissions on cluster resources": "Define and enforce access permissions on cluster resources",
    "Constrain workload security context and admission": "Constrain workload security context and admission",
    "Demonstrate and maintain regulatory compliance posture": "Demonstrate and maintain regulatory compliance posture",
    "Monitor, audit, and investigate security-relevant cluster activity": "Monitor, audit, and investigate security-relevant cluster activity",
    "Manage platform and ingress TLS certificates": "Manage platform and ingress TLS certificates",
}

jsonl_path = OUT / "security-auth-jtbd.jsonl"
csv_path = OUT / "security-auth-jtbd.csv"

with open(jsonl_path, "w", encoding="utf-8") as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")

cols = [
    "doc",
    "section",
    "job_statement",
    "job_type",
    "persona",
    "job_map_stage",
    "granularity",
    "parent_job",
    "prerequisites",
    "related_jobs",
    "desired_outcomes",
    "evidence",
    "notes",
    "validation_status",
    "validation_flags",
]

with open(csv_path, "w", encoding="utf-8", newline="") as f:
    w = csv.DictWriter(f, fieldnames=cols, extrasaction="ignore")
    w.writeheader()
    for r in records:
        row = {k: r.get(k, "") for k in cols}
        for arr in ("prerequisites", "related_jobs", "desired_outcomes", "validation_flags"):
            if isinstance(row.get(arr), list):
                row[arr] = "; ".join(row[arr]) if row[arr] else ""
        if row.get("parent_job") is None:
            row["parent_job"] = ""
        w.writerow(row)

main = sum(1 for r in records if r["granularity"] == "main_job")
stories = sum(1 for r in records if r["granularity"] == "user_story")
print(f"Wrote {len(records)} records ({main} main_job, {stories} user_story)")
print(f"  {jsonl_path}")
print(f"  {csv_path}")
