// Module included in the following assemblies:
//
// * authentication/identity_providers/configuring-gitlab-identity-provider.adoc

:_mod-docs-content-type: PROCEDURE
[id="identity-provider-gitlab-CR_{context}"]
= Creating a GitLab identity provider
// = Sample GitLab CR

// TODO: short desc + better intro
The following custom resource (CR) shows the parameters and acceptable values for a GitLab identity provider.

.Prerequisites

* TODO

.Procedure

// TODO: Consider creating the config map and secret as part of this procedure.

. Create the GitLab...

.GitLab CR
[source,yaml]
----
apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: gitlabidp
    mappingMethod: claim
    type: GitLab
    gitlab:
      clientID: {...}
      clientSecret:
        name: gitlab-secret
      url: https://gitlab.com
      ca: <6>
        name: ca-config-map
----
+
where:

`spec.identityProviders.name`:: Specifies the GitLab provider name. This provider name is prefixed to the GitLab numeric user ID to form an
identity name. It is also used to build the callback URL.
`spec.identityProviders.mappingMethod`:: Specifies how mappings are established between this provider's identities and `User` objects.
`spec.identityProviders.gitlab.clientID`:: Specifies the client ID of a
link:https://docs.gitlab.com/ce/api/oauth2.html[registered GitLab OAuth application]. The application must be configured with a callback URL of `\https://oauth-openshift.apps.<cluster_name>.<cluster_domain>/oauth2callback/<idp_provider_name>`.
`spec.identityProviders.gitlab.clientSecret.name`:: Specifies a reference to an {product-title} `Secret` object containing the client secret issued by GitLab.
`spec.identityProviders.gitlab.url`:: Specifies the host URL of a GitLab provider. This could either be `\https://gitlab.com/` or any other self-hosted instance of GitLab.
`spec.identityProviders.gitlab.ca`:: Specifies a reference to an {product-title} `ConfigMap` object containing the PEM-encoded certificate authority bundle to use in validating server certificates for the configured URL. This value is optional.

See "Identity provider parameters" for information about parameters, such as `mappingMethod`, that are common to all identity providers.
