// Module included in the following assemblies:
//
// * nodes/pods/nodes-pods-secrets-store.adoc

:_mod-docs-content-type: CONCEPT
[id="secrets-store-providers_{context}"]
= Secrets store providers

The following secrets store providers are available for use with the {secrets-store-operator}:

* AWS Secrets Manager
* AWS Systems Manager Parameter Store
* Azure Key Vault
* HashiCorp Vault

[IMPORTANT]
====
Red Hat has tested integration with these providers, but does not

Red Hat does not provide
====


////
When we say following providers are available for use https://docs.openshift.com/container-platform/4.16/nodes/pods/nodes-pods-secrets-store.html#secrets-store-providers_nodes-pods-secrets-store Can we not say following providers have been validated on OpenShift, please see RedHat's 3rd party support policy for coverage around these components https://access.redhat.com/third-party-software-support (edited)

Hence it is important to add the note that the Provider that are listed as supported have been validated on OpenShift but the actual support should come from the Provider's organization






Mounting secrets from HashiCorp Vault by using the {secrets-store-operator} has been tested with the following cloud providers:

* Amazon Web Services (AWS)
* Microsoft Azure

Other cloud providers might work, but have not been tested yet. Additional cloud providers might be tested in the future.

////
