:_mod-docs-content-type: ASSEMBLY
[id="logging-anp-policy"]
= Logging for AdminNetworkPolicy rules
include::_attributes/common-attributes.adoc[]
:context: logging-network-policy

toc::[]

As a cluster administrator, you can configure audit logging for your cluster and enable logging for one or more namespaces. {product-title} produces audit logs for both egress firewalls and network policies.

[NOTE]
====
Audit logging is available for only the xref:../../../networking/ovn_kubernetes_network_provider/about-ovn-kubernetes.adoc#about-ovn-kubernetes[OVN-Kubernetes network plugin].
====

include::modules/nw-anp-audit-logging-concept.adoc[leveloffset=+1]

[id="anp-policy-audit-configuration-{context}"]
== Audit configuration

The configuration for audit logging is specified as part of the OVN-Kubernetes cluster network provider configuration. The following YAML illustrates the default values for the audit logging:

.Audit logging configuration
[source,yaml]
----
apiVersion: operator.openshift.io/v1
kind: Network
metadata:
  name: cluster
spec:
  defaultNetwork:
    ovnKubernetesConfig:
      policyAuditConfig:
        destination: "null"
        maxFileSize: 50
        rateLimit: 20
        syslogFacility: local0
----

The following table describes the configuration fields for audit logging.

include::modules/nw-operator-cr.adoc[tag=policy-audit]
