[id="replacing-failed-master-host"]
= Replacing a failed master host
include::modules/common-attributes.adoc[]
:context: replacing-failed-master-host

toc::[]

This document describes the process to replace a single etcd member. This procedure assumes that there is still an etcd quorum in the cluster.

[NOTE]
====
If you have lost the majority of your master hosts, leading to etcd quorum loss, then you must follow the disaster recovery procedure to xref:../backup_and_restore/disaster_recovery/scenario-1-infra-recovery.adoc#dr-infrastructure-recovery[recover from lost master hosts] instead of this procedure.

If the TLS certificates are not valid on the member being replaced, then you must follow the procedure to xref:../backup_and_restore/disaster_recovery/scenario-3-expired-certs.adoc#dr-recovering-expired-certs[recover from expired control plane certificates] instead of this procedure.
====

// Replacing a single unhealthy member
include::modules/restore-replace-single-member.adoc[leveloffset=+1]
