[id="replacing-unhealthy-etcd-member"]
= Replacing an unhealthy etcd member
include::modules/common-attributes.adoc[]
:context: replacing-unhealthy-etcd-member

toc::[]

This document describes the process to replace a single unhealthy etcd member.

This procedure assumes that there is still an etcd quorum in the cluster. The process to replace the unhealthy member depends on whether the etcd member is stopped, or whether it is running but etcd is crashlooping.

[NOTE]
====
If you have lost the majority of your master hosts, leading to etcd quorum loss, then you must follow the disaster recovery procedure to xref:../backup_and_restore/disaster_recovery/scenario-2-restoring-cluster-state.adoc#dr-restoring-cluster-state[restore to a previous cluster state] instead of this procedure.

If the TLS certificates are not valid on the member being replaced, then you must follow the procedure to xref:../backup_and_restore/disaster_recovery/scenario-3-expired-certs.adoc#dr-recovering-expired-certs[recover from expired control plane certificates] instead of this procedure.
====

.Prerequisites

* Take an xref:../backup_and_restore/backing-up-etcd.adoc#backing-up-etcd-data_backup-etcd[etcd backup] prior to replacing an unhealthy etcd member.

// Identifying an unhealthy etcd member
include::modules/restore-identify-unhealthy-etcd-member.adoc[leveloffset=+1]

// Determining the state of the unhealthy etcd member
include::modules/restore-determine-state-etcd-member.adoc[leveloffset=+1]

== Replacing the unhealthy etcd member

Depending on the state of your unhealthy etcd member, either follow the steps to xref:../backup_and_restore/replacing-unhealthy-etcd-member.adoc#restore-replace-stopped-etcd-member_replacing-unhealthy-etcd-member[replace a stopped or failed etcd member] or to xref:../backup_and_restore/replacing-unhealthy-etcd-member.adoc#restore-replace-crashlooping-etcd-member_replacing-unhealthy-etcd-member[replace a crashlooping etcd member].

// Replacing a stopped or failed etcd member
include::modules/restore-replace-stopped-etcd-member.adoc[leveloffset=+2]

// Replacing a crashlooping etcd member
include::modules/restore-replace-crashlooping-etcd-member.adoc[leveloffset=+2]
