:_content-type: ASSEMBLY
[id="cert-types-kubelet-ca-certificates"]
= Kubelet CA certificates
include::_attributes/common-attributes.adoc[]
:context: cert-types-kubelet-ca-certificates

toc::[]

== Purpose

The kubelet certificate authority (CA) certificate... TODO

== Location

`/etc/kubernetes/kubelet-ca.crt` certificate authority (CA) ?

kube-apiserver-to-kubelet-client-ca config map in the openshift-kube-apiserver-operator namespace?

// from KCS on how to initiate renewal
kube-apiserver-to-kubelet-signer secret in the openshift-kube-apiserver-operator namespace?

// Example location from another file:
// The user-provided certificates must be provided in a `kubernetes.io/tls` type `Secret` in the `openshift-config` namespace. Update the API server cluster configuration, the `apiserver/cluster` resource, to enable the use of the user-provided certificate.

== Management

These certificates are managed by the system and not the user.

== Expiration

Kubelet CA certificates expire after 365 days.

== Renewal

The Kubernetes API Server Operator automatically generates a new `kube-apiserver-to-kubelet-signer` CA certificate at 292 days. The old CA certificate is removed after 365 days. Nodes are not rebooted when  a kubelet CA certificate is renewed or removed.

Cluster administrators can manually renew the kubelet CA certificate by running the following command:

[source,terminal]
----
$ oc annotate -n openshift-kube-apiserver-operator secret kube-apiserver-to-kubelet-signer auth.openshift.io/certificate-not-after-
----
